spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/duke_quartz?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: duke
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:D:/work/files

duke:
  sqllog:
    enabled: true
  redisson:
    enabled: false
  swagger:
    enabled: true #开启swagger,默认为开启
    title: quartz api
    description: 定时任务（quartz）项目服务
    version:
    termsOfServiceUrl:
    license:
    licenseUrl:
    basePackage: com.duke.microservice.quartz